defmodule Eatsbot.Repo.Migrations.Users do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:telegram_bot, primary_key: false) do
      add :id, :text, null: false, primary_key: true
      add :status, :text, null: false
      add :deliveries_id, {:array, :uuid}

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:telegram_bot)
  end
end
