defmodule Eatsbot.Repo.Migrations.DeliveriesNullable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deliveries) do
      modify :to_address, :text, null: false
      modify :to_longitude, :float, null: false
      modify :to_latitude, :float, null: false
    end
  end

  def down do
    alter table(:deliveries) do
      modify :to_latitude, :float, null: true
      modify :to_longitude, :float, null: true
      modify :to_address, :text, null: true
    end
  end
end
