defmodule Eatsbot.Repo.Migrations.DeliveriesAuthKeys do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deliveries) do
      modify :public_auth_key, :uuid, default: fragment("uuid_generate_v7()")
      modify :private_auth_key, :uuid, default: fragment("uuid_generate_v7()")
    end
  end

  def down do
    alter table(:deliveries) do
      modify :private_auth_key, :uuid, default: nil
      modify :public_auth_key, :uuid, default: nil
    end
  end
end
