defmodule Eatsbot.Repo.Migrations.OptionIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:options, [:name, :product_id], name: "options_unique_option_index")
  end

  def down do
    drop_if_exists unique_index(:options, [:name, :product_id],
                     name: "options_unique_option_index"
                   )
  end
end
