= Use Nix with Devenv for dev environments

- Status: accepted
- Date: 2025-01-07

== Context and Problem Statement

We want to declaratively define system dependencies (such as Elixir) and services (such as Postgres) to improve developer experience by streamlining setup and ensuring consistency.

== Considered Options

- https://devenv.sh/[Nix with Devenv]: Tool based on the Nix package manager that allows declaratively defining system dependencies and services.
- https://nix.dev/concepts/flakes.html[Nix Flakes]: Lower level abstraction over Nix that allows creating dev shells with the system dependencies necessary to run the project. It lacks higher-level abstractions for managing services like Postgres.
- https://www.docker.com/[Docker]: Tool that allows running development containers locally. Heavier in resource usage.
- https://github.com/features/codespaces[Github Codespaces]: Cloud hosted dev environment that runs an instance of Visual Studio Code in a browser. Relies on Github's cloud services. Devenv can generate a devcontainer.json that's compatible with it.

== Examples

- https://elixirforum.com/t/flake-nix-phoenix-postgresql/52622[Nix + Phoenix].
- https://github.com/nix-giant/nix-dev-templates/blob/fd35732623c251098239ef29fbdee63a78103f36/elixir/phoenix/flake.nix[Nix Phoenix Template].

== Questions

=== Can we use Dev Containers?

A https://code.visualstudio.com/docs/devcontainers/containers[devcontainer.json file] can be used as well?. Maybe we can support both *Nix* and *Docker Dev Container*, so Windows devs can have a dev environment too without _WSL_.

==== Answer

Devenv has a https://devenv.sh/integrations/codespaces-devcontainer/[devcontainer integration] which generates a __devcontainer.json__ file using the same configuration as __devenv.nix__.

=== What about Github Actions?

We will use Nix for Github Actions too?

==== Answer

No. Github Actions will be used the traditional way, but will match Elixir versions.
It's best to use the standarized approach as detailed here https://fly.io/docs/elixir/advanced-guides/github-actions-elixir-ci-cd/[Elixir Github Actions CI CD]. Maybe in the future this can be migrated to Nix, but is not a priority.

=== Release Dockerfile?

Phoenix generates a https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Release.html#module-docker[Dockerfile] with the command `mix phx.gen.release`. This would be used?.

==== Answer

Yes. The generated `Dockerfile` from Phoenix will be used for release. Nix Devenv is only used in development environments and not production settings.

== Decision Outcome

Chosen option: "`Nix with Devenv`", because

- Declarative and reproducible dev environments.
- Devenv allows managing services such as Postgres in a per-project basis.
- More lightweight than containers.
- Doesn't depend on external services such as Github.

== Consequences

All system dependencies will be handled in the devenv.nix file at the root of the project. Contributors will need to install Nix and Devenv, but this upfront effort will reduce issues with setting up the environment in the future and ensure reproducibility.

This approach may complicate setup on systems using native Windows without WSL, due to Nix lacking support for it, but using `devcontainer.json` can help with this limitation.

Github Actions will not use Nix. Nix will be used only for Dev Environments.

A _Dockerfile_ generated by Phoenix will be used for production releases.
