= Setting Up a Development Environment

We recommend using __Devenv__ to manage system dependencies and services. After cloning the repository, the `devenv.nix` file at the root of the project creates a reproducible development environment.

== Options to Run Devenv

1. Installing *Nix* https://devenv.sh/getting-started/[Follow the steps on this page.] and *Devenv*.

2. Using a Dev Container: https://code.visualstudio.com/docs/devcontainers/containers#_quick-start-open-an-existing-folder-in-a-container[Follow the steps on this page.] This repository includes a `devcontainer.json` file with *Devenv*.

[NOTE]
====
Tested with 'devenv-1.3.1'
====

== After Setting Up Devenv

- Enter a shell:  

[source, bash]
----
$ devenv shell
----

- Start services (for example, Postgres):  

[source, bash]
----
$ devenv up
----

- Set up the project (after entering shell):

[source, bash]
----
$ mix setup
----

[NOTE]
====
These commands are available in the project *Makefile*
====

== Troubleshoot

=== Error: You're not a trusted user of the Nix store.

This means that the file `/etc/nix/nix.conf` lacks the trusted users configuration.

- 1. Open the file with write privileges. 

[source, bash]
----
$ sudo vim /etc/nix/nix.conf
----

- 2. Add the trusted users.

[source, text]
----
trusted-users = root camilowser
----

- 3. Reboot nix service

[source, bash]
----
sudo launchctl kickstart -k system/org.nixos.nix-daemon
----

== Direnv

Install https://direnv.net/docs/installation.html#from-system-packages[Direnv] to automatically load _Devenv_ on entering the directory and load other system settings.
Check https://devenv.sh/automatic-shell-activation/[Automatic Shell Activation] docs.

.Step 1: Install direnv
[source, bash]
----
$ curl -sfL https://direnv.net/install.sh | bash
----

[NOTE]
====
Or use your package manager
# apt install -y direnv
====


.Step 2: Allow direnv
[source, bash]
----
direnv allow
----

.Step 3: Add to ~/.zshrc
[source, bash]
----
# Add to ohmyzsh plugins
plugins=(git direnv)

# Add zsh direnv eval
eval "$(direnv hook zsh)"
----

== Environment Variables

When using commands like `devenv shell` the `--impure` flag must be used.

- `NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1`: Will allow install unsupported packages. For example `inotify-tools` is not supported in _MacOS_ (darwin). Compilation is not garanteed though.

=== devenv.local.nix

This file is used to load environment variables in _Devenv_. Use it to store
API keys and other important data. An example file is provided as `devenv.local.nix.example`. Check https://devenv.sh/files-and-variables/#devenvlocalnix[Devlocal docs].

[source, js]
----
{pkgs, lib, inputs, ...}:
{
  env.MY_API_TOKEN="abc1234";
  env.LC_ALL="es_CL.UTF-8";
}
----

== Debian

Debian separates some needed libraries such as ssl. If there are some problems you can install them by using:

[source, bash]
----
$ sudo apt install -y erlang-ssl
----
