defmodule Tololo.Repo.Migrations.DiscountRules do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variants) do
      add :discount_rules, {:array, :map}, default: []
    end

    alter table(:products) do
      add :discount_rules, {:array, :map}, default: []
    end
  end

  def down do
    alter table(:products) do
      remove :discount_rules
    end

    alter table(:variants) do
      remove :discount_rules
    end
  end
end
