defmodule Tololo.Repo.Migrations.ValueIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:option_values, [:value, :option_id],
             name: "option_values_unique_value_index"
           )
  end

  def down do
    drop_if_exists unique_index(:option_values, [:value, :option_id],
                     name: "option_values_unique_value_index"
                   )
  end
end
