defmodule Tololo.Repo.Migrations.VariantUpdate do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:variants) do
      add :option_value_ids, {:array, :text}
    end

    create unique_index(:variants, [:option_value_ids, :product_id],
             name: "variants_unique_variant_index"
           )
  end

  def down do
    drop_if_exists unique_index(:variants, [:option_value_ids, :product_id],
                     name: "variants_unique_variant_index"
                   )

    alter table(:variants) do
      remove :option_value_ids
    end
  end
end
