defmodule Tololo.Repo.Migrations.Deliveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deliveries) do
      add :current_latitude, :float
      add :current_longitude, :float
    end
  end

  def down do
    alter table(:deliveries) do
      remove :current_longitude
      remove :current_latitude
    end
  end
end
