defmodule Tololo.Repo.Migrations.Deliveries do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deliveries) do
      modify :state, :text, default: "Init"
    end
  end

  def down do
    alter table(:deliveries) do
      modify :state, :text, default: nil
    end
  end
end
