defmodule Tololo.Repo.Migrations.DeliveriesDisplayId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:deliveries) do
      add :display_id, :text
    end

    create index(:deliveries, [:display_id])
  end

  def down do
    alter table(:deliveries) do
      remove :display_id
    end
  end
end
