=== Use Asciidoc Architectural Decision Records

- Status: accepted
- Date: 2024-09-30

==== Context and Problem Statement

We want to record architectural decisions made in this project
independent whether decisions concern the architecture ("`architectural
decision record`"), the code, or other fields. Which format and
structure should these records follow?

==== Considered Options

* https://adr.github.io/madr/[MADR] 4.0.0 – The Markdown Architectural
Decision Records
* http://thinkrelevance.com/blog/2011/11/15/documenting-architecture-decisions[Michael
Nygard’s template] – The first incarnation of the term "`ADR`"
* https://www.infoq.com/articles/sustainable-architectural-design-decisions[Sustainable
Architectural Decisions] – The Y-Statements
* Other templates listed at
https://github.com/joelparkerhenderson/architecture_decision_record
* Formless – No conventions for file format and structure

==== Decision Outcome

Chosen option: "`MADR 4.0.0`", because

* Implicit assumptions should be made explicit. Design documentation is
important to enable people understanding the decisions later on. See
also https://doi.org/10.1109/TSE.1986.6312940["`A rational design
process: How and why to fake it`"].
* MADR allows for structured capturing of any decision.
* The MADR format is lean and fits our development style.
* The MADR structure is comprehensible and facilitates usage &
maintenance.
* The MADR project is vivid.
* Can transpile it to ASCIIDoc with https://pandoc.org/try/[Pandoc]

==== Consequences

Using _Asciidoc_ enables using documentation tools such as https://antora.org/[Antora Docs]
in the future.