schema {
  mutation: RootMutationType
  query: RootQueryType
}

enum DeliveryStateChangesSortField {
  ID
  OLD_STATE
  NEW_STATE
  COMMENT
}

input DeliveryStateChangesFilterComment {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  like: String
  ilike: String
}

input DeliveryStateChangesFilterNewState {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String!]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  like: String
  ilike: String
}

input DeliveryStateChangesFilterOldState {
  isNil: Boolean
  eq: String
  notEq: String
  in: [String]
  lessThan: String
  greaterThan: String
  lessThanOrEqual: String
  greaterThanOrEqual: String
  like: String
  ilike: String
}

input DeliveryStateChangesFilterId {
  isNil: Boolean
  eq: ID
  notEq: ID
  in: [ID!]
  lessThan: ID
  greaterThan: ID
  lessThanOrEqual: ID
  greaterThanOrEqual: ID
}

input DeliveryStateChangesFilterInput {
  and: [DeliveryStateChangesFilterInput!]
  or: [DeliveryStateChangesFilterInput!]
  not: [DeliveryStateChangesFilterInput!]
  id: DeliveryStateChangesFilterId
  oldState: DeliveryStateChangesFilterOldState
  newState: DeliveryStateChangesFilterNewState
  comment: DeliveryStateChangesFilterComment
}

input DeliveryStateChangesSortInput {
  order: SortOrder
  field: DeliveryStateChangesSortField!
}

type DeliveryStateChanges {
  id: ID!
  oldState: String
  newState: String!
  comment: String
}

"The result of the :update_location mutation"
type UpdateLocationResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input UpdateLocationInput {
  currentLatitude: Float
  currentLongitude: Float
}

"The result of the :update_state mutation"
type UpdateStateResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input UpdateStateInput {
  state: String
}

"The result of the :init_delivery mutation"
type InitDeliveryResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input InitDeliveryInput {
  deliveryPerson: JsonString
  deliveryOrder: JsonString
  toLatitude: Float!
  toLongitude: Float!
  toName: String
  toAddress: String!
  toPhone: String
  toNotes: String
}

type Delivery {
  id: ID!
  displayId: String
  state: String!
  privateAuthKey: ID
  publicAuthKey: ID
  deliveryPerson: JsonString
  deliveryOrder: JsonString
  fromLatitude: Float
  fromLongitude: Float
  currentLatitude: Float
  currentLongitude: Float
  fromName: String
  toLatitude: Float!
  toLongitude: Float!
  toName: String
  toAddress: String!
  toPhone: String
  toNotes: String
  deliveryStartedAt: Date
  deliveryEndedAt: Date
  stateHistory(
    "How to sort the records in the response"
    sort: [DeliveryStateChangesSortInput]

    "A filter to limit the results"
    filter: DeliveryStateChangesFilterInput

    "The number of records to return."
    limit: Int

    "The number of records to skip."
    offset: Int
  ): [DeliveryStateChanges!]!
}

enum SortOrder {
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
}

"An error generated by a failed mutation"
type MutationError {
  "The human readable error message"
  message: String

  "A shorter error message, with vars not replaced"
  shortMessage: String

  "Replacements for the short message"
  vars: Json

  "An error code for the given error"
  code: String

  "The field or fields that produced the error"
  fields: [String!]
}

type RootQueryType {
  """
  Hello! This is a sample query to verify that AshGraphql has been set up correctly.
  Remove me once you have a query of your own!
  """
  sayHello: String

  getDelivery(
    "The id of the record"
    id: ID!
  ): Delivery
}

type RootMutationType {
  initDelivery(input: InitDeliveryInput!): InitDeliveryResult!
  updateState(id: ID!, input: UpdateStateInput): UpdateStateResult!
  updateLocation(id: ID!, input: UpdateLocationInput): UpdateLocationResult!
}

"""
The `Json` scalar type represents arbitrary json string data, represented as UTF-8
character sequences. The Json type is most often used to represent a free-form
human-readable json string.
"""
scalar JsonString

"""
The `Json` scalar type represents arbitrary json string data, represented as UTF-8
character sequences. The Json type is most often used to represent a free-form
human-readable json string.
"""
scalar Json

"""
The `Date` scalar type represents a date. The Date appears in a JSON
response as an ISO8601 formatted string, without a time component.
"""
scalar Date
