schema {
  mutation: RootMutationType
  query: RootQueryType
}

"The result of the :update_location mutation"
type UpdateLocationResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input UpdateLocationInput {
  fromLatitude: Float
  fromLongitude: Float
}

"The result of the :update_state mutation"
type UpdateStateResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input UpdateStateInput {
  state: String
}

"The result of the :init_delivery mutation"
type InitDeliveryResult {
  "The successful result of the mutation"
  result: Delivery

  "Any errors generated, if the mutation failed"
  errors: [MutationError!]!
}

input InitDeliveryInput {
  deliveryPerson: JsonString
  deliveryOrder: JsonString
  fromLatitude: Float
  fromLongitude: Float
  fromName: String
  toLatitude: Float
  toLongitude: Float
  toName: String
  toAddress: String
  toPhone: String
  toNotes: String
}

type Delivery {
  "A unique identifier"
  id: ID!

  state: String!

  privateAuthKey: ID!

  publicAuthKey: ID!

  deliveryPerson: JsonString

  deliveryOrder: JsonString

  fromLatitude: Float

  fromLongitude: Float

  fromName: String

  toLatitude: Float

  toLongitude: Float

  toName: String

  toAddress: String

  toPhone: String

  toNotes: String

  deliveryStartedAt: Date

  deliveryEndedAt: Date
}

"An error generated by a failed mutation"
type MutationError {
  "The human readable error message"
  message: String

  "A shorter error message, with vars not replaced"
  shortMessage: String

  "Replacements for the short message"
  vars: Json

  "An error code for the given error"
  code: String

  "The field or fields that produced the error"
  fields: [String!]
}

type RootQueryType {
  """
  Hello! This is a sample query to verify that AshGraphql has been set up correctly.
  Remove me once you have a query of your own!
  """
  sayHello: String

  getDelivery(
    "The id of the record"
    id: ID!
  ): Delivery
}

type RootMutationType {
  initDelivery(input: InitDeliveryInput): InitDeliveryResult!
  updateState(id: ID!, input: UpdateStateInput): UpdateStateResult!
  updateLocation(id: ID!, input: UpdateLocationInput): UpdateLocationResult!
}

"""
The `Json` scalar type represents arbitrary json string data, represented as UTF-8
character sequences. The Json type is most often used to represent a free-form
human-readable json string.
"""
scalar JsonString

"""
The `Json` scalar type represents arbitrary json string data, represented as UTF-8
character sequences. The Json type is most often used to represent a free-form
human-readable json string.
"""
scalar Json

"""
The `Date` scalar type represents a date. The Date appears in a JSON
response as an ISO8601 formatted string, without a time component.
"""
scalar Date
