=== Use  Collective Code Construction Contract (C4)

- Status: accepted
- Date: 2024-10-08

==== Context

This project shall use the https://rfc.zeromq.org/spec/42/[Collective Code Construction Contract (C4)] for all code changes.
The Collective Code Construction Contract (C4) is an evolution of the https://docs.github.com/es/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests[github.com Fork + Pull] Model, aimed at providing an optimal collaboration model for free software projects. 

> "Everyone, without distinction or discrimination, SHALL have an equal right to become a Contributor under the terms of this contract."

1. Check for https://github.com/ElixirCL/tololo/issues[open issues] or https://github.com/ElixirCL/tololo/issues/new/choose[open a new issue] to start a discussion around a problem.
2. Issues SHALL be named as "Problem: description of the problem".
3. Fork the https://github.com/ElixirCL/tololo[tololo] repository on GitHub to start making your changes
4. If possible, write a test which shows that the problem was solved.
5. Send a pull request.
6. Pull requests SHALL be named as "Solution: description of your solution"
7. Your pull request is merged and you are added to the list of contributors

Please see:

- https://www.youtube.com/watch?v=_QF9sFJGJuc[BUILD STUFF'14: Pieter Hintjens - One Weird Trick for Making Perfect Software]

==== Decision Outcome

C4 provides a standard process for contributing, evaluating and discussing improvements on software projects. It defines specific technical requirements for projects like a style guide, unit tests, git and similar platforms. It also establishes different personas for projects, with clear and distinct duties. C4 specifies a process for documenting and discussing issues including seeking consensus and clear descriptions, use of “pull requests” and systematic reviews.

