= Use Trunk Based Development and Conventional Commits

- Status: accepted
- Date: 2025-01-13

== Context

In order to standarize contributions and commit messages we will use https://trunkbaseddevelopment.com/[Trunk Based Development] and https://www.conventionalcommits.org/en/v1.0.0/[Conventional Commits].

_TBD_ is a source-control branching model, where developers collaborate on code in a single branch called ‘main’, resist any pressure to create other long-lived development branches by employing documented techniques. They therefore avoid merge hell, do not break the build, and live happily ever after.

.Flow
1. Update to latest main code. `git pull origin main`.
2. Create a new branch `git checkout -b my-change`.
3. Add changes `git add *` and commits `git commit -m 'my changes'`.
4. Send changes to branch `git push origin my-change`
5. Create a new PR. Follow *Conventional Commits* in the Title.
6. Request approval from other contributor.
7. Github action will enable *Squash Commit* if all the automatic tests pass.
8. Once approved and solved any issue found the PR creator must apply *Squash Commits* using *Conventional Commits* and fill the body with the details.
9. Close the related issue (if any) and delete the used branch.

[IMPORTANT]
====
Is recommended that the original person merges the PR. The approver will only approve the PR, but not merge it.
Since the original author can detect unexpected changes before merging and after approval (for example a merge conflict)
that must be resolved.
====

The _Conventional Commits_ specification is a lightweight convention on top of commit messages. It provides an easy set of rules for creating an explicit commit history; which makes it easier to write automated tools on top of. This convention dovetails with SemVer, by describing the features, fixes, and breaking changes made in commit messages.

The commit message should be structured as follows:

[source, text]
----
<type>[(optional scope)][optional !]: <description>

[optional body]

[optional footer(s)]
----

The commit categories will be (based on https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional[@commitlint/config-conventional]):

- **chore**: Another change that do not fits any other category.
- **refactor**:  Modify or delete existing code.
- **feat**: Implements a new feature.
- **docs**: Modify or creates documentation.
- **fix**: Fix a bug.
- **test**: Adds or improves tests.

[IMPORTANT]
====
All casing in the category and scope must be lowercase.
====

[IMPORTANT]
====
All merge commits must reference the pull request number in the squash message.
Once merged the sender branch will be deleted.
====

=== Examples

[source, text]
----
feat: allow provided config object to extend other configs in #232

feat!: send an email to the customer when a product is shipped in #412

feat(api)!: send an email to the customer when a product is shipped in #42

chore!: drop support for Node 6 in #24
----

== Decision

We will use _Trunk Based Development_, as a branch strategy and _Conventional Commits_ as a commit message standarization.

== Consequences

- Conventional commits will only be required inside the *Squash Commit* merge option inside the _Pull Request_. The developer can add as many commits and any format it needs. But the final *Squash Commit* message must follow _Conventional Commits_ and reference the Pull Request number and a summary of the changes inside its body.

- Pull Request must have at least 1 approval of another developer before merge them inside main.

- Pull Request must always be updated with the latest main version and do not have merge conflicts.

- Pull Request must pass the test suite before merge to `main`.

- `main` branch must always be runnable. Pull Request must not break `main`.

- Each commit on `main` will trigger a new build action that will release a "nightly version" that will update the semver.