name: Fly Reset
on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ssh console -C "/app/bin/eatsbot eval Eatsbot.Release.reset"
        working-directory: ./eatsbot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_SSH }}

